package Panels;

import Controlador.CtrCompra;
import dashboardapp.MainApp;
import static dashboardapp.MainApp.getPnlInicio;
import static dashboardapp.MainApp.mpPlato;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adrian11124
 */
public class Inicio extends javax.swing.JPanel {

    public Inicio() {
        initComponents();
        getListNombrePlato();
        getCompras();
    }
    
    public static void getCompras(){
        tbl_contentCompras.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 16));
        DefaultTableModel modelo = (DefaultTableModel) tbl_contentCompras.getModel();
        for (Modelo.Compra c : MainApp.StkCompras) {
            modelo.addRow(new Object[]{c.getPlato(), c.getValor(), c.getFecha()});
        }
    }
    
    public static void ComprarPlato(){  
        CtrCompra.Comprar(""+cbx_nombrePlato.getSelectedItem(), lblTotalPagar.getText());
    }
    
    public static void getListNombrePlato(){
        for (String item : mpPlato.keySet()) {
            cbx_nombrePlato.addItem(item);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_nombrePlato = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        sp_cantidad = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblTotalPagar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_aDescripcionIni = new javax.swing.JTextArea();
        lbl_precioUnitario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_contentCompras = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(656, 2));

        cbx_nombrePlato.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cbx_nombrePlato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione plato..." }));
        cbx_nombrePlato.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_nombrePlatoItemStateChanged(evt);
            }
        });
        cbx_nombrePlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_nombrePlatoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setText("Cantidad:");

        sp_cantidad.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        sp_cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sp_cantidadStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Total a Pagar::");

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton2.setText("Confirmar Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblTotalPagar.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lblTotalPagar.setText("$");

        txt_aDescripcionIni.setEditable(false);
        txt_aDescripcionIni.setColumns(20);
        txt_aDescripcionIni.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_aDescripcionIni.setRows(5);
        jScrollPane2.setViewportView(txt_aDescripcionIni);

        lbl_precioUnitario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        tbl_contentCompras.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tbl_contentCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLATO", "VALOR DE COMPRA", "FECHA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_contentCompras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_precioUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbx_nombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(sp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_nombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(sp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbl_precioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalPagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_nombrePlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_nombrePlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_nombrePlatoActionPerformed

    private void cbx_nombrePlatoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_nombrePlatoItemStateChanged
        if(!String.valueOf(cbx_nombrePlato.getSelectedItem()).equals("Seleccione plato...")){
            String key = ""+cbx_nombrePlato.getSelectedItem();
            String description = mpPlato.get(key).getDescripcion();
           txt_aDescripcionIni.setText(description); 
           lbl_precioUnitario.setText("$ "+mpPlato.get(key).getPrecio());
        }else{
            txt_aDescripcionIni.setText(""); 
            lbl_precioUnitario.setText("");
        }
    }//GEN-LAST:event_cbx_nombrePlatoItemStateChanged

    private void sp_cantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sp_cantidadStateChanged
        String key = ""+cbx_nombrePlato.getSelectedItem();
        Double precioUnitario = mpPlato.get(key).getPrecio();
        int cantidad =  (int) sp_cantidad.getValue();
        Double total = cantidad * precioUnitario;
        lblTotalPagar.setText("$"+total);
    }//GEN-LAST:event_sp_cantidadStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ComprarPlato();
        getPnlInicio();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cbx_nombrePlato;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lblTotalPagar;
    private javax.swing.JLabel lbl_precioUnitario;
    private javax.swing.JSpinner sp_cantidad;
    private static javax.swing.JTable tbl_contentCompras;
    public static javax.swing.JTextArea txt_aDescripcionIni;
    // End of variables declaration//GEN-END:variables
}
