package Panels;

import Controlador.CtrPlato;
import Modelo.Plato;
import dashboardapp.MainApp;

/**
 *
 * @author adrian11124
 */
public class subViews extends javax.swing.JPanel {

    /**
     * Creates new form subViews
     */
    public subViews() {
        initComponents();
    }

    public static void editPlato() {
        MainApp.getPnlAgregar();
        Plato plato = CtrPlato.getOnePlato(txt_v_nombre.getText());
        Agregar.txt_id.setText("" + plato.getId());
        Agregar.txt_nombre.setText(plato.getNombre());
        Agregar.txt_precio.setText("" + plato.getPrecio());
        Agregar.txt_aDescripcion.setText(plato.getDescripcion());
    }

    public static void deletePlato() {
        CtrPlato.deletePlato(txt_v_nombre.getText());
        MainApp.getPnlViewsPlato();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_av_descripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_v_nombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btn_v_delete = new javax.swing.JButton();
        btn_v_edit = new javax.swing.JButton();
        lbl_v_id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_v_precio = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_av_descripcion.setEditable(false);
        txt_av_descripcion.setColumns(20);
        txt_av_descripcion.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_av_descripcion.setRows(5);
        jScrollPane1.setViewportView(txt_av_descripcion);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Descripcion:");

        txt_v_nombre.setEditable(false);
        txt_v_nombre.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        btn_v_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        btn_v_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_v_deleteActionPerformed(evt);
            }
        });

        btn_v_edit.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        btn_v_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_v_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        btn_v_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_v_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(39, Short.MAX_VALUE)
                                .addComponent(btn_v_edit)
                                .addGap(18, 18, 18)
                                .addComponent(btn_v_delete)
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 22, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_v_delete, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn_v_edit, javax.swing.GroupLayout.Alignment.TRAILING))));

        lbl_v_id.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_v_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Precio: ");

        txt_v_precio.setEditable(false);
        txt_v_precio.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271,
                                                Short.MAX_VALUE)
                                        .addComponent(txt_v_nombre))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_v_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 155,
                                                        Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_v_id, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_v_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(txt_v_nombre,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(txt_v_precio,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 73,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_v_editActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_v_editActionPerformed
        editPlato();
    }// GEN-LAST:event_btn_v_editActionPerformed

    private void btn_v_deleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_v_deleteActionPerformed
        deletePlato();
    }// GEN-LAST:event_btn_v_deleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_v_delete;
    public static javax.swing.JButton btn_v_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lbl_v_id;
    public static javax.swing.JTextArea txt_av_descripcion;
    public static javax.swing.JTextField txt_v_nombre;
    public static javax.swing.JTextField txt_v_precio;
    // End of variables declaration//GEN-END:variables
}
