package Panels;

import Modelo.Plato;
import dashboardapp.MainApp;
import javax.swing.BoxLayout;

/**
 *
 * @author adrian11124
 */
public class ViewsPlato extends javax.swing.JPanel {

    /**
     * Creates new form ViewsPlato
     */
    public ViewsPlato() {
        initComponents();
        pnl_contentViews.setLayout(new BoxLayout(pnl_contentViews, BoxLayout.Y_AXIS));
        addComponents();

    }

    public static void addComponents() {
        for (String key : MainApp.mpPlato.keySet()) {
            Plato plato = MainApp.mpPlato.get(key);

            addMiniComponents(plato);
        }
        pnl_contentViews.revalidate();
        pnl_contentViews.repaint();
    }

    public static void addMiniComponents(Plato plato) {
        subViews mini = new subViews();
        subViews.txt_v_nombre.setText(plato.getNombre());
        subViews.txt_v_precio.setText("$ " + plato.getPrecio());
        subViews.txt_av_descripcion.setText(plato.getDescripcion());
        subViews.lbl_v_id.setText("" + plato.getId());
        pnl_contentViews.add(mini);
    }

    public static void buscarPlato() {
        try {
            Plato plato = MainApp.mpPlato.get("" + txt_buscar.getText());
            pnl_contentViews.removeAll();
            addMiniComponents(plato);
        } catch (Exception e) {
            MainApp.getPnlViewsPlato();
        }
        pnl_contentViews.revalidate();
        pnl_contentViews.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_buscar = new javax.swing.JTextField();
        lbl_buscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnl_contentViews = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(656, 2));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_buscar.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        lbl_buscar.setIcon(new javax.swing.ImageIcon("\\img\\search24.png")); // NOI18N
        lbl_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_buscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_contentViews.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_contentViewsLayout = new javax.swing.GroupLayout(pnl_contentViews);
        pnl_contentViews.setLayout(pnl_contentViewsLayout);
        pnl_contentViewsLayout.setHorizontalGroup(
            pnl_contentViewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        pnl_contentViewsLayout.setVerticalGroup(
            pnl_contentViewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnl_contentViews);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_buscarMouseClicked
        buscarPlato();
    }//GEN-LAST:event_lbl_buscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_buscar;
    public static javax.swing.JPanel pnl_contentViews;
    public static javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
